places_list = [
"Musée du Louvre",
"Tour Eiffel",
"Musée d'Orsay",
"Centre Pompidou",
"Musée de l'Orangerie",
"Musée Rodin",
"Musée Picasso",
"Musée du Quai Branly",
"Musée de l'Armée",
"Musée des Arts Décoratifs",
"Musée Marmottan Monet",
"Musée Jacquemart-André",
"Musée Nissim de Camondo",
"Musée Carnavalet",
"Musée de la Vie Romantique",
"Musée Cernuschi",
"Musée Guimet",
"Musée Bourdelle",
"Musée Zadkine",
"Musée d'Art Moderne de la Ville de Paris",
"Musée de Montmartre",
"Musée de la Chasse et de la Nature",
"Musée de l'Homme",
"Musée des Arts et Métiers",
"Musée de la Monnaie",
"Musée de Cluny",
"Musée de la Musique",
"Musée de la Poste",
"Musée de la Publicité",
"Musée de la Mode et du Textile",
"Musée de la Poupée",
"Musée de la Magie",
"Musée de la Contrefaçon",
"Musée de l'Érotisme",
"Musée de l'Eventail",
"Musée de l'Institut du Monde Arabe",
"Arc de Triomphe",
"Panthéon",
"Sainte-Chapelle",
"Conciergerie",
"Catacombes de Paris",
"Château de Vincennes",
"Palais de la Découverte",
"Cité des Sciences et de l'Industrie",
"Aquarium de Paris",
"Parc Zoologique de Paris",
"Grande Galerie de l'Évolution",
"Palais de Tokyo",
"Fondation Louis Vuitton",
"Palais Garnier",
"Opéra Bastille",
"Philharmonie de Paris",
"Théâtre du Châtelet",
"Théâtre de la Ville",
"La Villette",
"Grand Palais Immersif",
"Atelier des Lumières",
"Musée Grévin",
"Musée des Égouts de Paris",
"Musée de l'Illusion",
"Musée Yves Saint Laurent",
"Musée du Parfum Fragonard",
"Musée de la Légion d'Honneur",
"Musée Curie",
"Musée d'Ennery",
"Musée de la Préfecture de Police",
"Musée de la Franc-Maçonnerie",
"Musée de la Libération de Paris",
"Musée Jean Moulin",
"Musée du Fumeur",
"Musée de la Serrure",
"Musée de l'Histoire de la Médecine",
"Musée de la Contrefaçon",
"Musée de la Gendarmerie",
"Musée de la Monnaie de Paris",
"Musée de la Vie Associative",
"Musée de la Résistance",
"Musée de la Carte à Jouer",
"Musée de la Photographie",
"Musée de la Sculpture en Plein Air",
"Musée de la Mode de la Ville de Paris",
"Musée de la Danse",
"Musée de la Musique Mécanique",
"Musée de la Nature et de la Chasse",
"Musée de la Marine",
"Musée de la Police",
"Musée de la Révolution",
"Musée de la Sorcellerie",
"Musée de la Télévision",
"Musée de la Vie Quotidienne",
"Musée de l'Architecture",
"Musée de l'Automobile",
"Musée de l'Éducation",
"Musée de l'Électricité",
"Musée de l'Enfance",
"Musée de l'Imprimerie",
"Musée de l'Informatique",
"Musée de l'Optique",
"Musée de l'Outillage",
"Musée de l'Urbanisme"
]
