places_list = [
    "Musée du Louvre",
    "Tour Eiffel",
    "Musée d'Orsay",
    "Centre Pompidou",
    "Muséum national d'Histoire naturelle",
    "Cité des sciences et de l'industrie",
    "Basilique du Sacré-Cœur",
    "Cathédrale Notre-Dame de Paris",
    "Musée du Quai Branly - Jacques Chirac",
    "Fondation Louis Vuitton",
    "Arc de Triomphe",
    "Sainte-Chapelle",
    "Musée de l'Armée (Hôtel des Invalides)",
    "Petit Palais",
    "Musée de l'Orangerie",
    "Panthéon",
    "Musée Rodin",
    "Musée Grévin",
    "Conciergerie",
    "Musée Picasso",
    "Champs-Élysées",
    "Quartier du Marais",
    "Quartier Latin",
    "Montmartre",
    "Place de la Concorde",
    "Place Vendôme",
    "Place des Vosges",
    "Boulevard Haussmann",
    "Rue de Rivoli",
    "Rue du Faubourg-Saint-Honoré",
    "Jardin du Luxembourg",
    "Jardin des Tuileries",
    "Parc des Buttes-Chaumont",
    "Parc Monceau",
    "Parc de la Villette",
    "Bois de Boulogne",
    "Bois de Vincennes",
    "Jardin des Plantes",
    "Parc Montsouris",
    "Jardin du Palais-Royal",
    "Opéra Garnier",
    "Philharmonie de Paris",
    "Théâtre du Châtelet",
    "Théâtre des Champs-Élysées",
    "La Villette",
    "Zénith Paris",
    "Olympia",
    "Salle Pleyel",
    "Théâtre Mogador",
    "Théâtre de la Ville",
    "Hôtel de Ville",
    "Palais Royal",
    "Conciergerie",
    "Palais de Justice",
    "Palais du Luxembourg",
    "Palais Bourbon",
    "Hôtel des Invalides",
    "Palais de l'Élysée",
    "Sorbonne",
    "Institut de France",
    "Catacombes de Paris",
    "Canal Saint-Martin",
    "Île de la Cité",
    "Île Saint-Louis",
    "Place de la Bastille",
    "Place de la République",
    "Place du Tertre",
    "Place Dauphine",
    "Place des Victoires",
    "Place de la Nation",
    "Château de Versailles",
    "Château de Fontainebleau",
    "Château de Vincennes"
]
